name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY dir

      - name: Install & build 🏗️
        run: | 
                cd dir
                npm install
                npm test  
                npm run build

      - name: Deploy 🚀
        run: |
                cd dir
                git config --global user.name "gh-pages"
                git config --global user.name "gh-pages@example.com"
                npm run deploy


